<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="HUY-PC" name="Railway.RegisterTest" tests="3" failures="1" timestamp="02 thg 12 2018 09:59:48 GMT" time="9.785" errors="0">
  <testcase name="TC11" time="2.292" classname="Railway.RegisterTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid password length.] but found [Invalid password length],
	expected [Invalid ID length.] but found [Invalid ID length]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Invalid password length.] but found [Invalid password length],
expected [Invalid ID length.] but found [Invalid ID length]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Railway.RegisterTest.TC11(RegisterTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC11 -->
  <testcase name="TC10" time="1.824" classname="Railway.RegisterTest"/>
  <testcase name="TC07" time="5.669" classname="Railway.RegisterTest"/>
</testsuite> <!-- Railway.RegisterTest -->
